### ISSUE TITLE
incompatible with 64bit LabVIEW

### ISSUE THREAD

**Issue by Flydroid** [yonicon/PentaPanesDemo-LV2023#1]
Hi @yonicon 

I found your demo yesterday on LinkedIn and it looked very cool.
Unfortunately I cannot try it because the Penta Panes ppl is 32bit. 
Would it be possible to add a 64bit version of the ppl?

**Comment by yonicon** [comment]
Hi Flydroid, 
Thank you for enlightening me regarding this. 
Of course you are right, a packed lib compiled in 32bit will not run in 64bit 
I should've thought of that. 

I've added a 64bit version of the demo. you can find it at - 
https://github.com/yonicon/PentaPanesDemo-LV2022-64bit

cheers 
Yoni
